steps:
- name: "gcr.io/cloud-builders/docker"
  timeout: 800s
  args:
  - build
  - "--tag=gcr.io/maawol-store-front/store-front-app"
  - "--file=./Dockerfile.prod"
  - .
images:
- "gcr.io/maawol-store-front/store-front-app"